[package]
name = "faux-expect"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "=1.0.60" # pinned for 1.38.0 compatibility
quote = "=1.0.28" # pinned for 1.38.0 compatibility
rustversion = "1.0.17"
