name: cross

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "17 3 * * *"

env:
  CARGO_TERM_COLOR: always
jobs:
  cross-test-i686:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - name: Install cross
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          toolchain: ${{ matrix.toolchain }}
          target: i686-unknown-linux-gnu
          args: "--no-default-features --verbose"
      - name: test with cross
        run: |
          for features in "" "--features std" "--features public_imp" "--features std,public_imp"; do
            for rustflags in "-D warnings" "-D warnings -C target-feature=+avx2" "-D warnings -C target-feature=+sse4.2"; do
              cargo clean; RUSTFLAGS=$rustflags /home/runner/work/_temp/cross +${{ matrix.toolchain }} test --no-default-features --verbose --target i686-unknown-linux-gnu $features
            done
          done
      - name: nightly-only test with cross
        run: |
          for rustflags in "-D warnings" "-D warnings -C target-feature=+avx2" "-D warnings -C target-feature=+sse4.2"; do
            cargo clean; RUSTFLAGS=$rustflags /home/runner/work/_temp/cross +${{ matrix.toolchain }} test --no-default-features --verbose --target i686-unknown-linux-gnu --all-features
          done
        if: ${{ matrix.toolchain == 'nightly' }}

  cross-test-aarch64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Cross test
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          toolchain: ${{ matrix.toolchain }}
          target: aarch64-unknown-linux-gnu
          args: "--no-default-features --verbose"
      - name: test with cross
        run: |
          for features in "" "--features std" "--features public_imp" "--features std,public_imp"; do
            cargo clean; /home/runner/work/_temp/cross +${{ matrix.toolchain }} test --no-default-features --verbose --target i686-unknown-linux-gnu $features
          done
      - name: nightly-only test with cross
        run: |
          cargo clean; /home/runner/work/_temp/cross +${{ matrix.toolchain }} test --no-default-features --verbose --target i686-unknown-linux-gnu --all-features
        if: ${{ matrix.toolchain == 'nightly' }}

  cross-test-armv7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: Cross test
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          toolchain: ${{ matrix.toolchain }}
          target: armv7-unknown-linux-gnueabihf
          args: "--no-default-features --verbose"
      - name: test with cross
        run: |
          for rustflags in "-D warnings" "-D warnings -Ctarget-feature=+neon"; do
            for features in "" "--features std" "--features public_imp" "--features std,public_imp"; do
              cargo clean; /home/runner/work/_temp/cross +${{ matrix.toolchain }} test --no-default-features --verbose --target armv7-unknown-linux-gnueabihf $features
            done
          done
      - name: test with cross with armv7_neon enabled
        run: |
          for rustflags in "-D warnings" "-D warnings -Ctarget-feature=+neon"; do
            for features in "--features armv7_neon" "--features armv7_neon,std" "--features armv7_neon,public_imp" "--features armv7_neon,std,public_imp" "--all-features"; do
              cargo clean; /home/runner/work/_temp/cross +${{ matrix.toolchain }} test --no-default-features --verbose --target armv7-unknown-linux-gnueabihf $features
            done
          done
        if: ${{ matrix.toolchain == 'nightly' }}
